name: Development Continuous Deployment

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/panchobot:dev .

      - name: Log into Docker and upload image
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push ${{secrets.DOCKER_USERNAME}}/panchobot:dev


  # deploy:
  #   needs: [ build-docker-image ]
  #   environment:
  #     name: 'Development'
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: SSH into VPS, pull docker image and run the image
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.PROD_SSH_HOST }}
  #         username: ${{ secrets.PROD_SSH_USER }}
  #         key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}
  #         script: |
  #           echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
  #           docker stop panchobot-prod
  #           docker rm panchobot-prod
  #           docker pull ${{ secrets.DOCKER_USERNAME }}/panchobot:dev
  #           docker run --restart=always -d --network=host --name panchobot-prod --env-file ${{ secrets.SECRET_PATH }} ${{ secrets.DOCKER_USERNAME }}/panchobot:dev

    
